### PR TITLE
Adds the possibility to customize (like use icons) the close button

### PR DESCRIPTION
**Pull request by ygorcosta**

### CODE REVIEW

**Comment by eduardolundgren** [comment]
LGTM. /cc @fernandosouza

**Comment by fernandosouza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by fernandosouza** [comment]
Done. @ygorcosta, @eduardolundgren.

I've created a patch by mistake. I didn't remove it because I have had already pushed it to master. That's why you will see 2 releases. Sorry.

**Comment by fernandosouza** [comment]
I've caught a failed test, but not related to this pull.

```html
<div class="alert alert-dismissible alert-success fade" role="alert">
  body
  <button type="button" class="close" aria-label="Close" data-onclick="data-onclick">
    <span aria-hidden="true">×</span>
  </button>
</div>
```

The value of the `data-onclick` in the snippet above should be `toggle`, but the component renders the same attribute name somehow.

We have to investigate it.

cc. @jbalsas, @brunobasto, @Robert-Frampton

**Comment by jbalsas** [comment]
I was running tests and I've seen the same issue in `metal-treeview`, in particular in https://github.com/metal/metal-treeview/blob/master/test/Treeview.js#L298

I'm trying to figure out what happened, but it is likely that we've released something that's introducing the bug...

**Comment by fernandosouza** [comment]
Yeah.

It's the same kind of test. https://github.com/metal/metal-alert/blob/master/test/Alert.js#L90

**Comment by jbalsas** [comment]
I think the issue is in https://github.com/metal/metal.js/blob/master/packages/metal-incremental-dom/src/render/attributes.js#L98. This should be 

```
fn.givenAsName_ = value
```

This was probably introduced in https://github.com/metal/metal.js/commit/652f185b03793b2c74c11a568e8a2ab9d522e547, but I wonder how come we've spent so long without realizing...

**Comment by jbalsas** [comment]
Well, this more or less explains it...

screen shot 2017-03-30 at 13 51 42

We have circumstantial coverage in there, but the test suite for `metal-incremental-dom/render/attributes` never tests those things.

**Comment by brunobasto** [comment]
Also, very few components have ci integration.

**Comment by jbalsas** [comment]
I've opened https://github.com/metal/metal.js/issues/222. @fernandosouza, could you take care of this one?

**Comment by fernandosouza** [comment]
Sure, @jbalsas. 😃 

Metal components have CI integration only in the `metal-components` repo, and Travis has caught this issue. [https://travis-ci.org/metal/metal-components](https://travis-ci.org/metal/metal-components) There are many failed tests that we have to take care of. I've scheduled Travis to run the tests weekly.

**Comment by jbalsas** [comment]
Good catch, @fernandosouza!

We definitely need something more visible and make sure we pay attention :)

**Pull request merged**
